# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import get_students_pb2 as get__students__pb2


class StudentsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StudentDetails = channel.unary_unary(
                '/Students/StudentDetails',
                request_serializer=get__students__pb2.get_student_id.SerializeToString,
                response_deserializer=get__students__pb2.return_student_details.FromString,
                )


class StudentsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StudentDetails(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StudentsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StudentDetails': grpc.unary_unary_rpc_method_handler(
                    servicer.StudentDetails,
                    request_deserializer=get__students__pb2.get_student_id.FromString,
                    response_serializer=get__students__pb2.return_student_details.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Students', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Students(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StudentDetails(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Students/StudentDetails',
            get__students__pb2.get_student_id.SerializeToString,
            get__students__pb2.return_student_details.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
